services:
  krakend:
    image: devopsfaith/krakend:watch
    volumes:
      - ".:/etc/krakend"
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    command: [ "run", "-dc", "krakend.json" ]
    depends_on:
      - auth
      - orders
      - jaeger
    networks:
      - my-network
  
  influxdb:
    image: influxdb:1.8.10
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend-dev"
      - "INFLUXDB_USER_PASSWORD=pas5w0rd"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - "8086:8086"
    networks:
      - my-network

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=memory
    networks:
      - my-network
  
  rabbitmq: 
    image: rabbitmq:3.12.0-rc.1-management-alpine
    container_name: rabbitmq
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my-network

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    ports:
      - '3000:3000'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb-primary
      - rabbitmq
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    networks:
      - my-network
  
  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: yarn start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - mongodb-primary
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    networks:
      - my-network
  
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: yarn start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongodb-primary
      - billing
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
    networks:
      - my-network
  
  mongodb-primary:
    image: mongo:5.0.0
    container_name: microservicio-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge